(function() {var implementors = {};
implementors["actix_web"] = ["impl&lt;T, A, H, U&gt; Handler&lt;<a class=\"struct\" href=\"actix_web/dev/struct.PauseServer.html\" title=\"struct actix_web::dev::PauseServer\">PauseServer</a>&gt; for <a class=\"struct\" href=\"actix_web/struct.HttpServer.html\" title=\"struct actix_web::HttpServer\">HttpServer</a>&lt;T, A, H, U&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://docs.rs/tokio-io/0.1/tokio_io/trait.AsyncRead.html\" title=\"trait tokio_io::AsyncRead\">AsyncRead</a> + <a class=\"trait\" href=\"https://docs.rs/tokio-io/0.1/tokio_io/trait.AsyncWrite.html\" title=\"trait tokio_io::AsyncWrite\">AsyncWrite</a> + 'static,<br>&nbsp;&nbsp;&nbsp;&nbsp;H: <a class=\"trait\" href=\"actix_web/dev/trait.HttpHandler.html\" title=\"trait actix_web::dev::HttpHandler\">HttpHandler</a> + 'static,<br>&nbsp;&nbsp;&nbsp;&nbsp;U: 'static,<br>&nbsp;&nbsp;&nbsp;&nbsp;A: 'static,&nbsp;</span>","impl&lt;T, A, H, U&gt; Handler&lt;<a class=\"struct\" href=\"actix_web/dev/struct.ResumeServer.html\" title=\"struct actix_web::dev::ResumeServer\">ResumeServer</a>&gt; for <a class=\"struct\" href=\"actix_web/struct.HttpServer.html\" title=\"struct actix_web::HttpServer\">HttpServer</a>&lt;T, A, H, U&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://docs.rs/tokio-io/0.1/tokio_io/trait.AsyncRead.html\" title=\"trait tokio_io::AsyncRead\">AsyncRead</a> + <a class=\"trait\" href=\"https://docs.rs/tokio-io/0.1/tokio_io/trait.AsyncWrite.html\" title=\"trait tokio_io::AsyncWrite\">AsyncWrite</a> + 'static,<br>&nbsp;&nbsp;&nbsp;&nbsp;H: <a class=\"trait\" href=\"actix_web/dev/trait.HttpHandler.html\" title=\"trait actix_web::dev::HttpHandler\">HttpHandler</a> + 'static,<br>&nbsp;&nbsp;&nbsp;&nbsp;U: 'static,<br>&nbsp;&nbsp;&nbsp;&nbsp;A: 'static,&nbsp;</span>","impl&lt;T, A, H, U&gt; Handler&lt;<a class=\"struct\" href=\"actix_web/dev/struct.StopServer.html\" title=\"struct actix_web::dev::StopServer\">StopServer</a>&gt; for <a class=\"struct\" href=\"actix_web/struct.HttpServer.html\" title=\"struct actix_web::HttpServer\">HttpServer</a>&lt;T, A, H, U&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://docs.rs/tokio-io/0.1/tokio_io/trait.AsyncRead.html\" title=\"trait tokio_io::AsyncRead\">AsyncRead</a> + <a class=\"trait\" href=\"https://docs.rs/tokio-io/0.1/tokio_io/trait.AsyncWrite.html\" title=\"trait tokio_io::AsyncWrite\">AsyncWrite</a> + 'static,<br>&nbsp;&nbsp;&nbsp;&nbsp;H: <a class=\"trait\" href=\"actix_web/dev/trait.HttpHandler.html\" title=\"trait actix_web::dev::HttpHandler\">HttpHandler</a> + 'static,<br>&nbsp;&nbsp;&nbsp;&nbsp;U: 'static,<br>&nbsp;&nbsp;&nbsp;&nbsp;A: 'static,&nbsp;</span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
